apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: demo-app01
  namespace: demo-poc
spec:
  encryptedData:
    demo-app01: AgBqyPDkgJCkr1XoCqxEuEwLcKOkMfDX4N3KZRZ1bFgt7INWge3N2fXCDJWwwn4zhTzVz7oRgueoLbDFt7ptM/lbZI1Nqgy3tVt0YKzRwDXnDgBhqt7nNw4Ellt9DXoBFpEsABBLvHx8MPfUDS8MklM2vo2+DcWNc9jl2BwCNP9oOKWPsmLY04WEq+hH6OY7aZJenwzvNwhC4QTrpPL19OX0QZjmGDV927a8XuaOOerL/oUlPepMr/rlfE3ktAiBTg8/llKGeU3HWrOEw61YU3O5eVMlqk6oSjBVJTdXI8nrSuqBTfT5JQ1BCmEYMLucLhKErEG6oExw10QU6w41JAOw005dZdJe7KeybPIAlZdaNdeo8OnRgEHR+chMSSVcla7t1piVpmFNdMMPpqcI/JomHLFCLdoV2nLbbyn5Lr/4RMjPPP0eJOhyGFqg3HBPRfIA4GuW/3mtlml0aA5BQsD4DV7kaUZq/4V3jmsFfvYg+a/NZpMZl2T3iPUL7Y8OXVLLiIuAHE0zB4jA/aWjD7CF/r/VfN6pjnmA18eQJ0NNBsGVjUBxEbH/UvJn2M2URCl/FnQCaW04mYUyc48WpbuDlkPr9t4kSG5fSMsWlYQz+Zm5CzgN0ul9mY3bBoIx7JdkWwTJPE/9pGCrVi1gkQFmLFUOz3XU+REYiUZYoxBkNLIbNMnMlbraK4EbI9H9D+tvTZsFwNEyX5nD
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: demo-app01
      namespace: demo-poc

